version: '3.9'

services:
  clientes:
    build:
      context: ./clientes_service
    container_name: clientes_service
    ports:
      - "8000:8000"
    environment:
      - USE_AWS=false

  servicios:
    build:
      context: ./servicios_service
    container_name: servicios_service
    ports:
      - "8001:8000"
    environment:
      - USE_AWS=false

  archivos:
    build:
      context: ./archivos_service
    container_name: archivos_service
    ports:
      - "8002:8000"
    environment:
      - USE_AWS=false

  consultas:
    build:
      context: ./consultas_service
    container_name: consultas_service
    ports:
      - "8003:8000"
    environment:
      - USE_AWS=false

  admin:
    build:
      context: ./admin_mejora_service
    container_name: admin_mejora_service
    ports:
      - "8004:8000"

  auth:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8005:8000"

networks:
  default:
    name: ddd2_network
